### ISSUE TITLE
Count distinct rejection/suggestion words

### ISSUE THREAD

**Issue by srz2** [srz2/BeginnerProjectBot#21]
Right now, i think the program counts the number of suggested words and rejection words but doesn't account for repeats

Example: `What project would be a good python project for me to start on?`

The project keyword should be counted only once and repeats should decrease the overall length of the phrase in the algorithm

**Comment by 1nF0rmed** [comment]
Hey!
If this issue hasn't been assigned to anyone then I would like to work on it

**Comment by srz2** [comment]
Sure go for it!

**Comment by 1nF0rmed** [comment]
Hey I've raised a PR #23 
Let me know if you have any questions.

**Comment by srz2** [comment]
Closed with #23
