### ISSUE TITLE
Move Sections of code to separate files

### ISSUE THREAD

**Issue by srz2** [srz2/BeginnerProjectBot#6]
This has really grown to 500+ lines. It's time to move some things to their own files

- the thread classes

I'm sure there can be other optimizations which can be made

**Comment by AbdulMAbdi** [comment]
Hey, I would like to help with this. I have been working on it and will make a pull request tomorrow if thats okay.

**Comment by srz2** [comment]
Absolutely, go for it!

I'll be glad to review your PR. Good luck.
